@drcmda no, not really. its simple RegExp https://regexr.com/3h9ib /[\(*\)]{1}/gim for example


documentDirectory: "file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540anonymous%252Frecord-the-earth-expo-ee809db7-f171-4bfd-8bee-975fcf2531dd/"

[2].Expo.Constants


"{
  "nativeAppVersion":null,
  "statusBarHeight":24,
  "supportedExpoSdks":[
    "34.0.0",
    "31.0.0",
    "32.0.0",
    "33.0.0"],
  "installationId":"59746b88-438a-467f-88cd-dd8c39dec0cf",
  "linkingUri":"exp://127.0.0.1:19000",
  "expoVersion":"2.12.0",
  "platform":{"android":{"versionCode":null}},
  "appOwnership":"expo",
  "systemVersion":"8.1.0",
  "sessionId":"a48642ae-7b3d-40ea-9556-73d01a5cc567",
  "systemFonts":["normal",
  "notoserif",
  "sans-serif",
  "sans-serif-light",
  "sans-serif-thin",
  "sans-serif-condensed",
  "sans-serif-medium",
  "serif",
  "Roboto",
  "monospace"],
  "intentUri":"exp://127.0.0.1:19000",
  "experienceUrl":"exp://127.0.0.1:19000",
  "isHeadless":false,
  "manifest":{"name":"RecordTheEarthExpo",
  "slug":"record-the-earth-expo",
  "description":"Updating RtE react-native app to be fully managed with expo.",
  "privacy":"unlisted",
  "sdkVersion":"34.0.0",
  "platforms":["ios",
  "android"],
  "entryPoint":"node_modules/expo/AppEntry.js",
  "splash":{"image":"./splash.png",
  "resizeMode":"contain",
  "backgroundColor":"#ffffff",
  "imageUrl":"http://127.0.0.1:19001/assets/./splash.png"},
  "androidShowExponentNotificationInShellApp":true,
  "version":"1.0.0",
  "orientation":"portrait",
  "primaryColor":"#cccccc",
  "icon":"./icon.png",
  "updates":{"fallbackToCacheTimeout":0},
  "assetBundlePatterns":["**/*"],
  "ios":{"supportsTablet":false,
  "splash":{"backgroundColor":"#ffffff",
  "resizeMode":"contain",
  "image":"./splash.png",
  "imageUrl":"http://127.0.0.1:19001/assets/./splash.png"}},
  "android":{"package":"org.recordtheearth.expo"},
  "githubUrl":"https://github.com/charrismatic/record-the-earth-reach-native",
  "extra":{},
  "rnCliPath":"",
  "packagerOpts":{"hostType":"localhost",
  "lanType":"ip",
  "dev":true,
  "minify":false,
  "urlRandomness":"5y-s99"},
  "xde":true,
  "developer":{"tool":"expo-cli",
  "projectRoot":"/data/projects/React_Projects/examples/expo-tabs/App"},
  "env":{"EXPO_DEBUG":"true"},
  "bundleUrl":"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false",
  "debuggerHost":"127.0.0.1:19001",
  "mainModuleName":"node_modules/expo/AppEntry",
  "logUrl":"http://127.0.0.1:19000/logs",
  "hostUri":"127.0.0.1:19000",
  "iconUrl":"http://127.0.0.1:19001/assets/./icon.png",
  "id":"@anonymous/record-the-earth-expo-ee809db7-f171-4bfd-8bee-975fcf2531dd",
  "loadedFromCache":false,
  "isVerified":true},
  "deviceYearClass":2013,
  "isDevice":true,
  "deviceName":"Nexus 5X",
  "isDetached":false,
  "nativeBuildVersion":115,
  "deviceId":"59746b88-438a-467f-88cd-dd8c39dec0cf",
  "linkingUrl":"exp://127.0.0.1:19000"}"
