#!/bin/bash

BASE_DIR="$(npm prefix)"
NPM_MODULE_DIR=node_modules
# REACT_MODULES_PATTERN=/react-*

# REACT_MODULES_PATH="$BASE_DIR/${REACT_TEMP_DIR}/${REACT_MODULES_PATTERN}"
# NPM_MODULE_PATH="${BASE_DIR}/${NPM_MODULE_DIR}"

# cd ${BASE_DIR}

patch-package \
&& rm -rf node_modules/react-navigation/node_modules/react-native \
&& rm -rf node_modules/react-navigation/node_modules/@types \
&& rm -rf node_modules/react-navigation/node_modules/examples \
&& rm -rf node_modules/react-navigation/node_modules/react-native-gesture-handler \
&& rm -rf node_modules/react-navigation/node_modules/react \
echo "Done."
