#!/bin/bash

BASE_DIR="$(npm prefix)"
RELEASE_DATE="$(date +'%Y%m%d%H%M%S')"
TMP_DIR=".tmp"
PUBLIC_DIR="public"
SYNC_FLAGS=""
OUTPUT_DEST="${PUBLIC_DIR}"

# =================================================================
#   SYNC STATIC: (LOADS STATIC ASSETS AND ASSET DIRECTORY SKELETON)
# =================================================================

if [[ $RUN_ENV_TEST == "yes" ]]; then

  SYNC_FLAGS="--dry-run"

fi

if [[ $RUN_VERBOSE == "yes" ]]; then

  echo -e "\nSyncing static assets (loads static assets and asset directory skeleton)\n"

  SYNC_FLAGS="$SYNC_FLAGS --human-readable --update --info=name,stats1,misc1,flist"

  echo -e "Flags: ${SYNC_FLAGS}\n"

  echo -e "  [SRC] ${BASE_DIR}/src/static/\n    --> ${BASE_DIR}/${TMP_DIR}/${PUBLIC_DIR}/ \n"

else

  echo -e "\n[Syncing static assets]\n"

fi

rsync ${SYNC_FLAGS} --recursive ${BASE_DIR}/src/static/  ${BASE_DIR}/${TMP_DIR}/${PUBLIC_DIR}/
