#!/bin/bash

# EXPO HELPER
# -------------
BASE_DIR="$(npm prefix)"

source ${BASE_DIR}/../.env

ts build --removeComments  --jsx react-native --module ESNext --target ESNEXT --pretty --declaration  **/*.ts **/*.tsx "$@"
