#!/bin/bash

INPUT=${1?"error input required"}
INPUT_DIR="$(basename $INPUT)"
INPUT_PARENT="$(basename "$(dirname $INPUT)")"
OUTDIR=$INPUT
EMBED_STYLES="yes"
BUILD_DIR=".build"
DIST_DIR=".dist"
DOCS_DIR=".docs"
DEST_BUILD="$OUTDIR/$BUILD_DIR"
DEST_DOCS="$OUTDIR/$DOCS_DIR"
DEST_DIST="$OUTDIR/$DIST_DIR"
EXAMPLE_CSS_SRC="$DEST_DIST"
EXAMPLE_HTML_SRC="$DEST_BUILD"
STYLEGUIDE_BODYBG="rgb(81,143,140)"

echo " build 2 docs ----"
# echo "INPUT- $INPUT"
# echo "INPUT_DIR- $INPUT_DIR"
# echo "BASE_DIR- $BASE_DIR"
# echo "EMBED_STYLES- $EMBED_STYLES"
# echo "OUTDIR- $OUTDIR"
# echo "DEST_BUILD- $DEST_BUILD"
# echo "DEST_DOC- $DEST_DOC"
# echo "DEST_DIST- $DEST_DIST"
# echo "EXAMPLE_CSS_SRC- $EXAMPLE_CSS_SRC"
# echo "EXAMPLE_HTML_SRC- $EXAMPLE_HTML_SRC"
# exit 0

_build_index () {
  find "$DOCS_DIR/" -name "*.html"  \
    -type f \
    ! -name ".build.html" \
    -printf "<li><a href=\"%P\">%P</a></li>\n" \
    > ".build/index.html"
}


example_styleguide_styles () {
  echo "body { background-color: $STYLEGUIDE_BODYBG; }"
  echo 'body { padding: 2em; max-width: 1000px; margin: auto;}
  .debug_outline_structure > * { outline: 1px solid #123; }
  .styleguide code { padding: 2px 4px; font-size: 90%; color: #1bbcff; background-color: #efefef; border-radius: 3px; }
  .styleguide pre { display: block; padding: 0 1em; margin: 1em 0; font-size: 1em; line-height: 1.5; color: #919191; background-color: #ececec; border: 1px solid #d5d5d5; }
  .styleguide pre code { padding: 0; font-size: inherit; color: inherit; white-space: pre-wrap; background-color: transparent; border-radius: 0; }
  .styleguide section .page-wrap { padding: 1em 0; overflow: unset; }
  .styleguide .code_examples .container { display: block; margin: 1em 0; border-bottom: 1px solid #84cc4e; padding: 1em 0; }
  .styleguide .code_examples .container__example { display: inline-block; margin: 1em 0; border: 1px dotted #cccccc; padding: 1em; background: #ffffff; }
  .styleguide .code_examples .container__example * { outline: 1px dashed #c28181; }
  .styleguide .code_examples .container__title { display: block; }
  .styleguide .flex_grid--5 > * { flex: 0 1 auto; margin: 0 .4em 0 0; }
  .styleguide .flex_grid--5 { justify-content: flex-start; }
  .styleguide .lp-section-content-wrap { margin-top: 0; }
  .styleguide_section .container { display: block; padding: 1em 2em; border: 1px solid #ccc; margin: 1em 0; border-bottom: 1px solid #84cc4e; background: #fff; }
  .styleguide_section .container__content { display: inline-block; margin: 1em 0; border: 1px dotted #ccc; padding: 1em; background: #fff; }
  .styleguide_section .container__name { display: block; }
  .styleguide_section .item__label { white-space: nowrap; background: white; padding: 3px; }
  .wireframe_guides * { outline: 1px dashed #c28181; }'
}


example_start_document () {
  echo '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="application-name" content="" />
<title></title>
<!-- <link rel="icon" type="image/svg+xml" href="http://www.w3.org/html/logo/downloads/HTML5_Badge.svg"> -->
<link rel="shortcut icon" href="/favicon.ico" />
<!-- <link href="css/styleguide.css" media="screen, projection" rel="stylesheet" type="text/css" /> -->
<!-- <script src="js/prism.js" type="text/javascript"></script> -->
<style>'

  example_styleguide_styles

  echo '</style>
<script type="text/javascript"></script>
</head>'
}


example_append_styles () {
  echo -e "<style>"
  if [ -f "$EXAMPLE_CSS_SRC/index.min.css" ]; then
    cat "$EXAMPLE_CSS_SRC/index.min.css"
  elif [ -f "$EXAMPLE_CSS_SRC/index.min.css" ]; then
    cat "$EXAMPLE_CSS_SRC/index.css"
  else
    echo "could not find module styles in $EXAMPLE_CSS_SRC"
  fi
  echo -e "\n</style>"
}

example_include_stylesheet () {
  echo -e "<link rel=\"stylesheet\" href=\styles.css\">\n"
}

example_begin_content () {
  echo '<body class="">
<div class="messages"></div>
  <div class="page visible">
    <main class="main" role="main">
      <section class="content" style="padding-bottom: 3em;">
       <div class="container">'
}



example_append_content () {
  if [ -f "$EXAMPLE_HTML_SRC/.build.html" ]; then
    cat "$EXAMPLE_HTML_SRC/.build.html"
  elif [ -f "$EXAMPLE_HTML_SRC/build.html" ]; then
    cat "$EXAMPLE_HTML_SRC/build.html"
  else
    echo "could not find module styles in $EXAMPLE_HTML_SRC"
  fi
}

example_close_content () {
  echo '       </div><!--END CONTAINER-->
      </section><!--END CONTENT-->
    </main>'
}

example_close_document () {
  echo '  <footer></footer>
  </div><!--END PAGE-->
</body>
</html>
'
}

# ////[\s\d\w\n\W]*////

_build_example () {
  example_start_document
  example_begin_content
  if [ $EMBED_STYLES = "yes" ]; then
    example_append_styles
  else
    example_include_stylesheet
  fi
  echo "<h1>$INPUT_PARENT/$INPUT_DIR</h1>"
  example_append_content
  example_close_content
  example_close_document
}


# MAIN

_build_example

exit 0
