export declare const DROPBOX: {
    AUTHORIZE_URL: string;
    GET_METADATA_URL: string;
    REVOKE_TOKEN_URL: string;
    UPLOAD_URL: string;
    DOWNLOAD_URL: string;
    API_RESULT_HEADER_NAME: string;
    CLIENT_MODIFIED_TIMESTAMP_KEY: string;
    ACCESS_TOKEN_STORAGE_KEY: string;
    ACCOUNT_ID_STORAGE_KEY: string;
    MOST_RECENT_BACKUP_TIMESTAMP_KEY: string;
    LAST_UPDATE_STATUS_KEY: string;
    UPDATE_STATUS_STARTED: string;
    UPDATE_STATUS_FINISHED: string;
    NO_SUCH_FILE_ERROR_SUBSTRING: string;
};
