// Methods
// clear
// isFocused

const TextInputProps = [
  'allowFontScaling',
  'autoCapitalize',
  'autoCompleteType',
  'autoCorrect',
  'autoFocus',
  'blurOnSubmit',
  'caretHidden',
  'clearButtonMode',
  'clearTextOnFocus',
  'contextMenuHidden',
  'dataDetectorTypes',
  'defaultValue',
  'disableFullscreenUI',
  'editable',
  'enablesReturnKeyAutomatically',
  'importantForAutofill',
  'inlineImageLeft',
  'inlineImagePadding',
  'inputAccessoryViewID',
  'keyboardAppearance',
  'keyboardType',
  'maxFontSizeMultiplier',
  'maxLength',
  'multiline',
  'numberOfLines',
  // events
  'onBlur',
  'onChange',
  'onChangeText',
  'onContentSizeChange',
  'onEndEditing',
  'onFocus',
  'onKeyPress',
  'onLayout',
  'onScroll',
  'onSelectionChange',
  'onSubmitEditing',
   //
  'placeholder',
  'placeholderTextColor',
  'rejectResponderTermination',
  'returnKeyLabel',
  'returnKeyType',
  'scrollEnabled',
  'secureTextEntry',
  'selection',
  'selectionColor',
  'selectionState',
  'selectTextOnFocus',
  'showSoftInputOnFocus',
  'spellCheck',
  {
    'style':  [
      'borderLeftWidth',
      'borderTopWidth',
      'borderRightWidth',
      'borderBottomWidth',
      'borderTopLeftRadius',
      'borderTopRightRadius',
      'borderBottomRightRadius',
      'borderBottomLeftRadius',
    ]
  },

  'textBreakStrategy',
  'textContentType',
  'underlineColorAndroid',
  'value'
];
