#!/bin/bash

BASE_DIR="$(npm prefix)"

BOOK_STATIC_DIR="static"
BOOK_CONFIG_DIR=".storybook"
BOOK_OUTPUT_DIR="deploy"

BOOK_PACKAGE_VERSION="$(npm run env | grep npm_package_version= | sed 's/npm_package_version=/v/')"

BOOK_DEPLOY_DIR="$BOOK_OUTPUT_DIR/current"
BOOK_ARCHIVE_DIR="$BOOK_OUTPUT_DIR/$BOOK_PACKAGE_VERSION"

# COMMAND OPTIONS
BOOK_FLAGS=" --no-dll --debug-webpack"


# ALLOW LOCAL .NPMRC OR .ENV FILE TO OVERRIDE
# PROJECT DEFAULTS
if [ -f "$(npm prefix)/.npmrc" ]; then
  echo "Loading project env"
  . "$(npm prefix)/.npmrc"
fi

# 1. BUILD TO TAGGED VERSION ARCHIVE FIRST
# 2. MOVE/UPDATE INTO DEPLOY REPOSITORY AFTER TEST
# 3. RSYNC AND BUMP VERSION ON NPM
# 4. TAG COMMIT IN GIT THEN PUSH CLEAN

echo ".bin/build-storybook
   config-dir $BOOK_CONFIG_DIR
   static-dir $BOOK_STATIC_DIR
   output-dir $BOOK_ARCHIVE_DIR
"

# start-storybook \ -p 9009 -o deploy-cache -s static --debug-webpack --no-dll --debug-webpack  --watch
$BASE_DIR/node_modules/.bin/build-storybook \
  $BOOK_FLAGS \
  --config-dir "$BOOK_CONFIG_DIR" \
  --static-dir "$BOOK_STATIC_DIR" \
  --output-dir "$BOOK_ARCHIVE_DIR"  \

## post export
# find  deploy/v0.1.1/ -name *.map -deletell ll
