#!/bin/bash

BASE_DIR="$(npm prefix)"

BOOK_STATIC_DIR="static"
BOOK_CONFIG_DIR=".storybook"

# COMMAND OPTIONS
BOOK_FLAGS=" --no-dll --debug-webpack"

# ALLOW LOCAL .NPMRC OR .ENV FILE TO OVERRIDE
# PROJECT DEFAULTS
if [ -f "$(npm prefix)/.npmrc" ]; then
  echo "Loading project env"
  . "$(npm prefix)/.npmrc"
fi

# 1. BUILD TO TAGGED VERSION ARCHIVE FIRST
# 2. MOVE/UPDATE INTO DEPLOY REPOSITORY AFTER TEST
# 3. RSYNC AND BUMP VERSION ON NPM
# 4. TAG COMMIT IN GIT THEN PUSH CLEAN

echo ".bin/start-storybook
 --config-dir $BOOK_CONFIG_DIR
 --static-dir $BOOK_STATIC_DIR
 --output-dir $BOOK_ARCHIVE_DIR
 --no-dll
 --debug-webpack
"

# start-storybook \ -p 9009 -o deploy-cache -s static --debug-webpack --no-dll --debug-webpack  --watch
$BASE_DIR/node_modules/.bin/start-storybook \
  $BOOK_FLAGS \
  --config-dir "$BOOK_CONFIG_DIR" \
  --static-dir "$BOOK_STATIC_DIR" \
