#!/bin/bash


BOOK_PACKAGE_VERSION="$(npm run env | grep npm_package_version= | sed 's/npm_package_version=/v/')"


_clean () {
   echo "processing $1"

   postcss "$1" --no-map -u postcss-discard-comments --replace
   echo "Removing comments"

   postcss "$1" --no-map -u postcss-single-line --replace
   echo "Reformatting single line operations"

   sed --in-place '/^$/d' "$1"
   echo "Removing unncessary newlines"

}

export -f _clean

## NO VARIABLES FOR PATHS WHEN DELETING FILES **

find "deploy/storybook/${BOOK_PACKAGE_VERSION}" -name "*.map" \
  -printf "deleting map files %P \n" \
  -delete


find "deploy/storybook/${BOOK_PACKAGE_VERSION}" -name "*.css" \
  -printf "%P \n" \
  -exec bash -c '_clean "$0"' {} \;


# postcss {} --no-map -u postcss-discard-comments --replace \; \
#   -exec postcss {} --no-map -u postcss-single-line --replace \; \
#   -exec sed --in-place '/^$/d' {} \;
