#!/bin/bash

BASE_DIR="$(npm prefix)"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

__clear_watchman_list () {
  watchman watch-del-all
}
__clear_metro_cachedir () {
  rm -rf $BASE_DIR/metro-bundler-cache-*
  # rm -rf /tmp/metro-bundler-cache-*
  npm start -- --reset-cache
}

__clear_metro_tmp_cache () {
  rm /tmp/haste-map-metro*
  find /tmp/ -type f -exec rm {} \;
  rm -rf /tmp/metro-cache/*
}


__clear_react_packager__() {
  rm -rf $BASE_DIR/./node_modules/react-native-packager-cache-*
}
__clear_react__() {
  rm -rf $BASE_DIR/./node_modules/react-*
}

__clear_npm_all__ () {
  rm -rf $BASE_DIR/./node_modules
}
__clear_npm_cache () {
  npm cache verify
}

__clear_npm_check () {
  npm cache clean
}
