#!/bin/bash

# ANDROID-BUILD
# -------------
# BUILD THE ANDROID PROJECT FROM THE ./android directory

BASE_DIR="$(npm prefix)"
ABD_PATH="${ANDROID_HOME}/platform-tools"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

# REACTOTRON
[[ ! -z $RUN_REACT_REACTOTRON ]] &&  ${ABD_PATH}/adb reverse tcp:9090 tcp:9090
# REACT DEVTOOLS
[[ ! -z $RUN_REACT_DEVTOOLS ]] && ${ABD_PATH}/adb reverse tcp:8097 tcp:8097
# CHROME
[[ ! -z $RUN_CHROMEDEVTOOLS ]] && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081
# REACT DEBUGGER
[[ ! -z $RUN_REACT_DEBUGGER ]] && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081

# REACT-NATIVE CLI
${ABD_PATH}/adb reverse tcp:19001 tcp:19001
${ABD_PATH}/adb reverse tcp:19000 tcp:19000

${ABD_PATH}/adb reverse --list
