#!/bin/bash

# ANDROID-BUILD
# -------------
# BUILD THE ANDROID PROJECT FROM THE ./android directory
# For anyone who is having issues with the first command (in cases like a text input which cannot be unfocused), an alternative is adb shell
# "input keyevent 82 && input keyevent 66 && input keyevent 66". It manually hits 'Reload' in the developer menu – Jonny Jul 10 at 19:31

RUN_SCRIPT_SRC="$(readlink -f -- $BASH_SOURCE)"
RUN_SCRIPT_DIR="$(dirname -- \"$RUN_SCRIPT_SRC\")"

BASE_DIR="$(npm prefix)"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

ANDROID_SERIAL="025abd11727717ac"
ABD_PATH="${ANDROID_HOME}/platform-tools"
ANDROID_SERIAL="$(${RUN_SCRIPT_DIR}/_adb_get_serial)"

echo "Shaking ANDROID_SERIAL $ANDROID_SERIAL"
# ${ABD_PATH}/adb -s ${ANDROID_SERIAL} shell input keyevent 82

${ABD_PATH}/adb shell input keyevent 82
