#!/bin/bash

# Android Debug Bridge version 1.0.41
# Version 29.0.2-5738569
# Installed as /data/projects/5_Android_Projects/AndroidSDK/platform-tools/adb
# # react
# #   -e <expr>, --regex=<expr>  Only print lines where the log message matches <expr>
# #   -m <count>, --max-count=<count> where <expr> is a regular expression
#         experience.ExperienceActivity to host.exp.exponent/host.exp.exponent.experience.ExperienceActivity#1
#         08-27 19:01:19.135 14525 14677 E unknown:ViewManager: 	at abi34_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
#         08-27 19:01:20.000 14525 14556 W OkHttpClient: A connection to http://127.0.0.1:19001/ was leaked. Did you forget to close a response body?
#         08-27 19:01:19.138 14525 14677 E unknown:ReactNative: 	at abi34_0_0.com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandle
#         facebook.react.bridge.WritableNativeMap abi34_0_0.com.facebook.react.bridge.Arguments.makeNativeMap(java.util.Map) due to JIT
#         global options:
#         Sets log print format verb and adverbs, where <format> is:
#   brief help long process raw tag thread threadtime time
# and individually flagged modifying adverbs can be added:
#   color descriptive epoch monotonic printable uid
#   usec UTC year zone
# Multiple -v parameters or comma separated list of format and
# format modifiers are allowed.
#  -a         listen on all network interfaces, not just localhost
#  -d         use USB device (error if multiple devices connected)
#  -e         use TCP/IP device (error if multiple TCP/IP devices available)
#  -s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)
#  -t ID      use device with given transport id
#  -H         name of adb server host [default=localhost]
#  -P         port of adb server [default=5037]
#  -L SOCKET  listen on given socket for adb server [default=tcp:localhost:5037
# logcat                   show device log (logcat --help for more)
# Usage: logcat [options] [filterspecs]
# options include:
#   -s              Set default filter to silent. Equivalent to filterspec '*:S'
#   -f <file>, --file=<file>               Log to file. Default is stdout
#   -r <kbytes>, --rotate-kbytes=<kbytes>
#                   Rotate log every kbytes. Requires -f optionWifiService:
#   -n <count>, --rotate-count=<count>
#                   Sets max number of rotated logs to <count>, default 4
#   --id=<id>       If the signature id for logging to file changes, then clear
#                   the fileset and continue
#   -v <format>, --format=<format>
#                   Sets log print format verb and adverbs, where <format> is:
#                     brief help long process raw tag thread threadtime time
#                   and individually flagged modifying adverbs can be added:
#                     color descriptive epoch monotonic printable uid
#                     usec UTC year zone
#                   Multiple -v parameters or comma separated list of format and
#                   format modifiers are allowed.
#   -D, --dividers  Print dividers between each log buffer
#   -c, --clear     Clear (flush) the entire log and exit
#                   if Log to File specified, clear fileset instead
#   -d              Dump the log and then exit (don't block)
#   -e <expr>, --regex=<expr>
#                   Only print lines where the log message matches <expr>
#                   where <expr> is a regular expression
#   -m <count>, --max-count=<count>
#                   Quit after printing <count> lines. This is meant to be
#                   paired with --regex, but will work on its own.
#   --print         Paired with --regex and --max-count to let content bypass
#                   regex filter but still stop at number of matches.
#   -t <count>      Print only the most recent <count> lines (implies -d)
#   -t '<time>'     Print most recent lines since specified time (implies -d)
#   -T <count>      Print only the most recent <count> lines (does not imply -d)
#   -T '<time>'     Print most recent lines since specified time (not imply -d)
#                   count is pure numerical, time is 'MM-DD hh:mm:ss.mmm...'
#                   'YYYY-MM-DD hh:mm:ss.mmm...' or 'sssss.mmm...' format
#   -g, --buffer-size                      Get the size of the ring buffer.
#   -G <size>, --buffer-size=<size>
#                   Set size of log ring buffer, may suffix with K or M.
#   -L, --last      Dump logs from prior to last reboot
#   -b <buffer>, --buffer=<buffer>         Request alternate ring buffer, 'main',
#                   'system', 'radio', 'events', 'crash', 'default' or 'all'.
#                   Multiple -b parameters or comma separated list of buffers are
#                   allowed. Buffers interleaved. Default -b main,system,crash.
#   -B, --binary    Output the log in binary.
#   -S, --statistics                       Output statistics.
#   -p, --prune     Print prune white and ~black list. Service is specified as
#                   UID, UID/PID or /PID. Weighed for quicker pruning if prefix
#                   with ~, otherwise weighed for longevity if unadorned. All
#                   other pruning activity is oldest first. Special case ~!
#                   represents an automatic quicker pruning for the noisiest
#                   UID as determined by the current statistics.
#   -P '<list> ...', --prune='<list> ...'
#                   Set prune white and ~black list, using same format as
#                   listed above. Must be quoted.
#   --pid=<pid>     Only prints logs from the given pid.
#   --wrap          Sleep for 2 hours or when buffer about to wrap whichever
#                   comes first. Improves efficiency of polling by providing
#                   an about-to-wrap wakeup.
# filterspecs are a series of <tag>[:priority]
# where <tag> is a log component tag (or * for all) and priority is:
#   V    Verbose (default for <tag>)
#   D    Debug (default for '*')
#   I    Info
#   W    Warn
#   E    Error
#   F    Fatal
#   S    Silent (suppress all output)
# '*' by itself means '*:D' and <tag> by itself means <tag>:V.
# If no '*' filterspec or -s on command line, all filter defaults to '*:V'.
# eg: '*:S <tag>' prints only <tag>, '<tag>:S' suppresses all <tag> log messages.
# If not specified on the command line, filterspec is set from ANDROID_LOG_TAGS.
# If not specified with -v on command line, format is set from ANDROID_PRINTF_LOG
# or defaults to "threadtime"
# RCT_METRO_PORT=8081

BASE_DIR="$(npm prefix)"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

[[ -z $ANDROID_HOME ]] && echo 'ANDROID_HOME is not set. Skipping command' && exit 0
ABD_PATH="${ANDROID_HOME}/platform-tools"
ANDROID_SERIAL="025abd11727717ac"

# SUPPRESS ALL '*:S'
${ABD_PATH}/adb logcat WifiService:S ConnectivityService:S ReactNative:V ReactNativeJS:V -v long,color,printable  -v monotonic,color,descriptive -vprocess,color
