#!/bin/bash

BASE_DIR="$(npm prefix)"

[[ -f .npmrc ]] && source .npmrc

# Android Debug Bridge version 1.0.41
# Version 29.0.2-5738569
# Installed as /data/projects/5_Android_Projects/AndroidSDK/platform-tools/adb
# global options:
#  -a         listen on all network interfaces, not just localhost
#  -d         use USB device (error if multiple devices connected)
#  -e         use TCP/IP device (error if multiple TCP/IP devices available)
#  -s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)
#  -t ID      use device with given transport id
#  -H         name of adb server host [default=localhost]
#  -P         port of adb server [default=5037]
#  -L SOCKET  listen on given socket for adb server [default=tcp:localhost:5037

[[ -z $ANDROID_HOME ]] && echo 'ANDROID_HOME is not set. Skipping command' && exit 0
ABD_PATH="${ANDROID_HOME}/platform-tools"

# 025abd11727717ac       device usb:3-3 product:bullhead model:Nexus_5X device:bullhead transport_id:11
ANDROID_SERIAL="025abd11727717ac"
ADB_DEVICE_IP="192.168.1.53"
ADB_DEVICE_PORT="5555"

_set_device_tcpip_port () {
  ${ABD_PATH}/adb tcpip ${ADB_DEVICE_PORT}
}


_connect_device_tcpip () {
  ${ABD_PATH}/adb connect ${ADB_DEVICE_IP}
}


${ABD_PATH}/adb devices -l

# if connected

_set_device_tcpip_port

_connect_device_tcpip

# else
#${ABD_PATH}/adb kill-server
#${ABD_PATH}/adb start-server
${ABD_PATH}/adb reconnect
