#!/bin/bash

# EXPO HELPER
# -------------
# device reverse tunnel        exp://127.0.0.1:19000
# Metro Bundler on                        port 19001
# RCT_METRO_PORTL                              :8081
# Expo DevTools is            http://localhost:19002
# --redirect-warnings=...                   write warnings to file instead of stderr
# --title=...                               the process title to use on startup
# --require=...                             module to preload (option can be repeated)
# --inspect[=[host:]port]                   activate inspector on host:port (default: 127.0.0.1:9229)
# --inspect-brk[=[host:]port]               activate inspector on host:port and break at start of user script
# --debug-port, --inspect-port=[host:]port  set host:port for inspector
# -                                         script read from stdin (default if no file name is provided, interactive mode if a tty)
# --                                        indicate the end of node options
unset REACT_EDITOR
unset REACT_DEBUGGER
set -a REACT_DEBUGGER

EXPO_HOST="localhost"
BASE_DIR="$(npm prefix)"
ABD_PATH="${ANDROID_HOME}/platform-tools"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

NODE_ENV="development"


echo "Checking Android path ..."

[[ -z $ANDROID_HOME ]] && echo 'ANDROID_HOME is not set. Skipping command' && exit 0

echo "Settings up device:"

npm run adb.devices

# TRYING TO CATCH ERRORS HERE SO WE CAN RECONNECT DEVICES
# BEFORE EXPO FAILS TO CONNECT AND WE END UP IN A BAD STATE.
DEVICE_EXIT_STATUS="$?"
# else
# fi
# if [ "$DEVICE_EXIT_STATUS" === "1" ]; ThemeScreen
# exit 0

if [ $DEVICE_EXIT_STATUS > 0 ]; then
  echo "Problem Connecting to device: $?"
  echo "Trying to fix the problem and reconnect automatically"
    npm run adb.reconnect
fi


npm run adb.reverse

echo "Settings up additional devtools..."

# REACTOTRON
if [ ! -z $RUN_REACT_REACTOTRON ]; then
  npm run react:reactotron &
fi

# REACT DEBUGGER
if [ ! -z $RUN_REACT_DEBUGGER ]; then
  REACT_DEBUGGER=${REACT_DEBUGGER} npm run react:debugger &
fi

# REACT DEVTOOLS
[[ ! -z $RUN_REACT_DEVTOOLS ]] && npm run react:devtools &


echo "
  NODE_DEBUG  ${NODE_DEBUG}
  NODE_ENV  ${NODE_ENV}
  NODE_OPTIONS  ${NODE_OPTIONS}
  NODE_PATH $NODE_PATH
  EXPO_DEBUG  ${EXPO_DEBUG}
  EXPO_HOST ${EXPO_HOST}
  REACT_DEBUGGER ${REACT_DEBUGGER}
  REACT_EDITOR  ${REACT_EDITOR}
  RUN_ENV ${RUN_ENV}
"

NODE_PATH="${NODE_PATH}" \
NODE_ENV="${NODE_ENV}" \
NODE_OPTIONS="${NODE_OPTIONS}" \
NODE_DEBUG="${NODE_DEBUG}" \
REACT_DEBUGGER=${REACT_DEBUGGER} \
REACT_EDITOR="${REACT_EDITOR}" \
EXPO_DEBUG="${EXPO_DEBUG}" \
  node ${BASE_DIR}/node_modules/.bin/expo start \
    --clear \
    --max-workers 7 \
    --no-minify \
    --no-https \
    --dev \
    --host ${EXPO_HOST} \
    --android
