#!/bin/bash

# -------------------------
# react-native run-android
# -------------------------
BASE_PATH="$(npm prefix)"
BASE_PATH="$(npm prefix)"

[[ -f .npmrc ]] && source .npmrc

NODE_RUN_ENV=""
NODE_RUN_FLAGS=""
# --config path::String
# --env
# --rulesdir
# --plugin
#  --watch-ignore RegExp        Regex string of folders to ignore when watching - default: /.git|node_modules|bower_components/
#  --watch-delay Int            Delay(ms) for watcher to wait to trigger re-lint - default: 300

# ESLINT-WATCH - GLOBAL INSTALL
${NODE_RUN_ENV} esw --color --debug --changed --watch
