#!/bin/bash

# UNMET PEER DEPENDENCY react-native-gesture-handler@*
# "invalid"
# "extraneous"
# "err!"
# "peer dep missing"
# "UNMET PEER DEPENDENCY"

npm ls | grep -vi optional | grep -i 'unmet peer'

# |  grep -i --color unmet
# npm ls | grep -vi optional | grep  -i "invalid\|err\|peer\|missing" | sort

#"install-peerdeps"

## List peer dependencies
#npm info react-native@latest peerDependencies

echo "$(find ./Components -maxdepth 3 -type d -printf \"%p\n\"
  && find ./Config -maxdepth 3 -type d -printf \"%p\n\"
  && find ./LifeCycle -maxdepth 3 -type d -printf \"%p\n\"
  && find ./Model -maxdepth 3 -type d -printf \"%p\n\"
  && find ./Screens -maxdepth 3 -type d -printf \"%p\n\"
  && find ./Theme -maxdepth 3 -type d -printf \"%p\n\"
  && find ./Utilities -maxdepth 3 -type d -printf \"%p\n\")"


LINT_DIRS="ComponAnim App.js app.json babel.config.js Components Config icon.png init.js LifeCycle Model node_modules package.json package-lock.json Screens splash.jpg Theme Utilities ents,Lib,LifeCycle,Theme,Utilities,Views,preload_modules,screens"
find ./Components -maxdepth 3 -type d -printf \"%p\n\" \
  && find ./Config -maxdepth 3 -type d -printf \"%p\n\" \
  && find ./LifeCycle -maxdepth 3 -type d -printf \"%p\n\" \
  && find ./Model -maxdepth 3 -type d -printf \"%p\n\" \
  && find ./Screens -maxdepth 3 -type d -printf \"%p\n\" \
  && find ./Theme -maxdepth 3 -type d -printf \"%p\n\" \
  && find ./Utilities -maxdepth 3 -type d -printf \"%p\n\""
