#!/bin/bash

BASE_PATH="$(npm prefix)"

[[ -f .npmrc ]] && source .npmrc

# react-native

${BASE_PATH}/./node_modules/react-native/local-cli/cli.js bundle \
    --entry-file index.js \
    --platform android \
    --dev false \
    --bundle-output android/main.jsbundle \
    --assets-dest android
